name: msgphp
recipe: lemp

config:
  php: 7.2
  webroot: public

proxy:
  pma:
    - pma.msgphp.lndo.site

services:
  appserver:
    config:
      server: config/lando/nginx.conf
  database:
    portforward: 3307
  pma:
    type: phpmyadmin
  elasticsearch:
    type: compose
    services:
      image: blacktop/elasticsearch:6.3
      command: /elastic-entrypoint.sh elasticsearch
      ports:
        - "9200:9200"

tooling:
  sf:
    service: appserver
    description: Run Symfony commands
    cmd: bin/console
  php:
    service: appserver
    description: Run PHP commands
    cmd: php
  composer:
    service: appserver
    description: Run Composer commands
    cmd: composer
  run:
    service: appserver
    description: Run any command
    cmd: ~

events:
  post-start:
    appserver: "composer install --working-dir=$LANDO_MOUNT"
