parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    App\Controller\:
        resource: '../src/Controller'
        tags: [controller.service_arguments]

    # API endpoints
    App\Api\Endpoint\:
        resource: '../src/Api/Endpoint'
        tags: [controller.service_arguments]

    # Console
    App\Console\ClassContextElementFactory: ~
    MsgPhp\Domain\Infra\Console\Context\ClassContextElementFactoryInterface: '@App\Console\ClassContextElementFactory'

    # Console Commands
    App\Console\Command\:
        resource: '../src/Console/Command'

    # Security
    App\Security\JwtTokenSubscriber: ~
    App\Security\OauthUserProvider: ~
    App\Security\OneTimeLoginAuthenticator: ~
    App\Security\PasswordConfirmation:
        arguments:
            '$secret': '%kernel.secret%'
    App\Security\RoleProvider: ~
    App\Security\UserChecker: ~

    # Messenger
    App\EventSubscriber\:
        resource: '../src/EventSubscriber'
